name: CI
on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: Testingland-R/workflows/.github/workflows/python_CI.yml@43687a519d7ed4a95ba6b4edb44d4e917a986021 # main
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
    with:
      python-version: '3.11'
      test-command: 'pytest --maxfail=1 --cov -v'
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
