name: Renovate auto approve call

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [dismissed]


jobs:
  Aprover_call:
    uses: Testingland-R/workflows/.github/workflows/auto-approve-renovate.yml@626cc04b74f5bfaf75359aae8616a325908a3e90 # main
    permissions:
      pull-requests: write
      contents: read
