name: Renovate auto approve call

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [dismissed]


jobs:
  Aprover_call:
    uses: Testingland-R/workflows/.github/workflows/auto-approve-renovate.yml@2f76782539aec2160b0fef744c8392a77970b68b # main
    permissions:
      pull-requests: write
      contents: read
