name: Renovate auto approve call

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [dismissed]


jobs:
  Aprover_call:
    uses: Testingland-R/workflows/.github/workflows/renovate-auto-approve.yml@4122384cadbd4d1a511011ea1f539f3f8602d0e7 # main
    permissions:
      pull-requests: write
      contents: read
