name: Executable Workflow
on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: roquevaamonde/workflows/.github/workflows/python_CI.yml@main
    with:
      python-version: '3.11'
    secrets:
      repo_token: ${{ secrets.REUSABLE_WORKFLOW_TOKEN }}
